LANGUAGES = ["English", "Deutsche", "Español", "Française", "Русский"]
TOPICS = [["Basics #1", "Basics #2", "Human", "Life", "Home", "City", "Food", "Earth & Nature", "Animals",
           "Education & sport", "Jobs"],
          ["Grundlagen #1", "Grundlagen #2", "Mensch", "Leben", "Haus", "Stadt", "Essen", "Erde & Natur", "Tiere",
           "Bildung & Sport", "Berufe "],
          ["Basics #1", "Basics #2", "Human", "Life", "Home", "City", "Food", "Earth & Nature", "Animals",
           "Education & sport", "Jobs"],
          ["Basics #1", "Basics #2", "Human", "Life", "Home", "City", "Food", "Earth & Nature", "Animals",
           "Education & sport", "Jobs"],
          ["Основы #1", "Основы #2", "Человек", "Жизнь", "Дом", "Город", "Еда", "Земля и природа", "Животные",
           "Образование и спорт", "Профессии"]
          ]
SUBTOPICS = [
    [
        ["Numbers 0 -9", "Numbers 10 - 19", "Numbers 20 - 1000", "Pronoun #1", "Pronoun #2", "Months #1",
         "Month #2 and Days", "Colors #1", "Colors #2 & materials #1", "Materials #2"],
        ["Questions", "Adjectives #1", "Adjectives #2", "Adjectives #3", "Adjectives #4", "Preposition", "Position",
         "Time", "Adverb #1", "Adverb #2"],
        ["Human #1", "Human #2", "Human #3", "Head #1", "Head #2", "Actions #1", "Actions #2", "Actions #3",
         "Actions #4", "Actions #5"],
        ["Family #1", "Family #2", "Hobby #1", "Hobby #2", "Hobby #3", "Relationship", "Work", "Routine", "Money",
         "Accidents"],
        ["Home #1", "Home #2", "Kitchen #1", "Kitchen #2", "Kitchen #3", "Bathroom & toilet #1", "Bathroom & toilet#2",
         "Bedroom", "Living room", "Dining room"],
        ["Buildings #1", "Buildings #2", "Buildings #3", "Buildings #4", "Buildings #5", "Buildings #6", "Street #1",
         "Street #2", "Transport #1", "Transport #2"],
        ["Vegetables #1", "Vegetables #2", "Fruits #1", "Fruits #2", "Berries", "Groats", "Nuts", "Meet & poultry",
         "Seafood & fish", "Drinks"],
        ["Planets & Space", "Earth #1", "Earth #2", "Earth #3", "Natural phenomena #1", "Natural phenomena #2",
         "Seasons and weather", "Plants", "Trees", "Flowers"],
        ["Pets", "Domestic animals", "Wild animals #1", "Wild animals #2", "Wild animals #3", "Wild animals #4",
         "Wild animals #5", "Birds #1", "Birds #2", "Insects"],
        ["Education #1", "Education #2", "Education #3", "Subject of study #1", "Subject of study #2", "Sport #1",
         "Sport #2",
         "Sport #3", "Sport #4", "Sport #5"],
        ["Jobs #1", "Jobs #2", "Jobs #3", "Jobs #4", "Jobs #5", "Jobs #6", "Jobs #7", "Jobs #8", "Jobs #9", "Jobs #10"]
    ],
    [
        ["Anzahlen 0–9", "Anzahlen 10–19", "Anzahlen 20–1000", "Pronomen #1", "Pronomen #2", "Monate #1",
         "Monat #2 & Tage", "Farben #1", "Farben #2 & Materialien #1", "Materialien #2"],
        ["Fragen", "Adjektive #1", "Adjektive #2", "Adjektive #3", "Adjektive #4", "Präposition", "Position", "Zeit",
         "Adverb #1", "Adverb # 2"],
        ["Mensch #1", "Mensch #2", "Mensch #3", "Kopf #1", "Kopf #2", "Aktionen #1", "Aktionen #2", "Aktionen #3",
         " Aktionen #4", "Aktionen #5"],
        ["Familie # 1", "Familie # 2", "Hobby # 1", "Hobby # 2", "Hobby # 3", "Beziehung", "Arbeit", "Routine", "Geld",
         " Unfälle"],
        ["Haus #1", "Haus #2", "Küche #1", "Küche #2", "Küche #3", "Bad & Toilette #1", "Bad & Toilette #2",
         "Schlafzimmer", "Wohnzimmer ", "Esszimmer"],
        ["Gebäude #1", "Gebäude #2", "Gebäude #3", "Gebäude #4", "Gebäude #5", "Gebäude #6", "Straße #1", "Straße #2",
         "  Fahrzeug #1", " Fahrzeug #2"],
        ["Gemüse #1", "Gemüse #2", "Obst #1", "Obst #2", "Beeren", "Grütze", "Nüsse", "Fleisch & Geflügel",
         "Meeresfrüchte & Fisch", " Getränke"],
        ["Planeten & Weltraum", "Erde #1", "Erde #2", "Erde #3", "Naturphänomene #1", "Naturphänomene #2",
         "Jahreszeiten & Wetter", "Pflanzen", "Bäume", " Blumen"],
        ["Haustiere", "Haustiere", "Wilde Tiere #1", "Wilde Tiere #2", "Wilde Tiere #3", "Wilde Tiere #4",
         "Wilde Tiere #5", "Vögel #1", "Vögel #2", "Insekten"],
        ["Bildung #1", "Bildung #2", "Bildung #3", "Studienfach #1", "Studienfach #2", "Sport #1", "Sport #2",
         "Sport #3",
         "Sport # 4", "Sport # 5"],
        ["Beruf #1", "Beruf #2", "Beruf #3", "Beruf #4", "Beruf #5", "Beruf #6", "Beruf #7", "Beruf #8", " Beruf #9",
         "Beruf #10"]
    ],
    [
        ["Numbers 0 -9", "Numbers 10 - 19", "Numbers 20 - 1000", "Pronoun #1", "Pronoun #2", "Months #1",
         "Month #2 and Days", "Colors #1", "Colors #2 & materials #1", "Materials #2"],
        ["Questions", "Adjectives #1", "Adjectives #2", "Adjectives #3", "Adjectives #4", "Preposition", "Position",
         "Time", "Adverb #1", "Adverb #2"],
        ["Human #1", "Human #2", "Human #3", "Head #1", "Head #2", "Actions #1", "Actions #2", "Actions #3",
         "Actions #4", "Actions #5"],
        ["Family #1", "Family #2", "Hobby #1", "Hobby #2", "Hobby #3", "Relationship", "Work", "Routine", "Money #1",
         "Accidents"],
        ["Home #1", "Home #2", "Kitchen #1", "Kitchen #2", "Kitchen #3", "Bathroom & toilet", "Bathroom & toilet",
         "Bedroom", "Living room", "Dining room"],
        ["Buildings #1", "Buildings #2", "Buildings #3", "Buildings #4", "Buildings #5", "Buildings #6", "Street #1",
         "Street #2", "Transport #1", "Transport #2"],
        ["Vegetables #1", "Vegetables #2", "Fruits #1", "Fruits #2", "Berries", "Groats", "Nuts", "Meet & poultry",
         "Seafood & fish", "Drinks"],
        ["Planets & Space", "Earth #1", "Earth #2", "Earth #3", "Natural phenomena", "Natural phenomena",
         "Seasons and weather", "Plants", "Trees", "Flowers"],
        ["Pets", "Domestic animals", "Wild animals #1", "Wild animals #2", "Wild animals #3", "Wild animals #4",
         "Wild animals #5", "Birds #1", "Birds #2", "Insects"],
        ["Education #1", "Education #2", "Education #3", "Subject of study #1", "Subject of study #2", "Sport #1",
         "Sport #2",
         "Sport #3", "Sport #4", "Sport #5"],
        ["Jobs #1", "Jobs #2", "Jobs #3", "Jobs #4", "Jobs #5", "Jobs #6", "Jobs #7", "Jobs #8", "Jobs #9", "Jobs #10"]
    ],
    [
        ["Numbers 0 -9", "Numbers 10 - 19", "Numbers 20 - 1000", "Pronoun #1", "Pronoun #2", "Months #1",
         "Month #2 and Days", "Colors #1", "Colors #2 & materials #1", "Materials #2"],
        ["Questions", "Adjectives #1", "Adjectives #2", "Adjectives #3", "Adjectives #4", "Preposition", "Position",
         "Time", "Adverb #1", "Adverb #2"],
        ["Human #1", "Human #2", "Human #3", "Head #1", "Head #2", "Actions #1", "Actions #2", "Actions #3",
         "Actions #4", "Actions #5"],
        ["Family #1", "Family #2", "Hobby #1", "Hobby #2", "Hobby #3", "Relationship", "Work", "Routine", "Money #1",
         "Accidents"],
        ["Home #1", "Home #2", "Kitchen #1", "Kitchen #2", "Kitchen #3", "Bathroom & toilet", "Bathroom & toilet",
         "Bedroom", "Living room", "Dining room"],
        ["Buildings #1", "Buildings #2", "Buildings #3", "Buildings #4", "Buildings #5", "Buildings #6", "Street #1",
         "Street #2", "Transport #1", "Transport #2"],
        ["Vegetables #1", "Vegetables #2", "Fruits #1", "Fruits #2", "Berries", "Groats", "Nuts", "Meet & poultry",
         "Seafood & fish", "Drinks"],
        ["Planets & Space", "Earth #1", "Earth #2", "Earth #3", "Natural phenomena", "Natural phenomena",
         "Seasons and weather", "Plants", "Trees", "Flowers"],
        ["Pets", "Domestic animals", "Wild animals #1", "Wild animals #2", "Wild animals #3", "Wild animals #4",
         "Wild animals #5", "Birds #1", "Birds #2", "Insects"],
        ["Education #1", "Education #2", "Education #3", "Subject of study #1", "Subject of study #2", "Sport #1",
         "Sport #2",
         "Sport #3", "Sport #4", "Sport #5"],
        ["Jobs #1", "Jobs #2", "Jobs #3", "Jobs #4", "Jobs #5", "Jobs #6", "Jobs #7", "Jobs #8", "Jobs #9", "Jobs #10"]
    ],
    [
        ["Числа 0–9", "Числа 10–19", "Числа 20–1000", "Местоимения #1", "Местоимения #2", "Месяцы #1", "Месяц #2 и дни",
         "Цвета #1", "Цвета. # 2 и материалы # 1 ", " Материалы # 2 "],
        ["Вопросы", "Прилагательные #1", "Прилагательные #2", "Прилагательные #3", "Прилагательные #4", "Предлог",
         "Позиция", "Время", "Наречие #1", "Наречие # 2 "],
        ["Человек #1", "Человек #2", "Человек #3", "Голова #1", "Голова #2", "Действия #1", "Действия #2",
         "Действия #3", " Действия # 4 ", " Действия # 5 "],
        ["Семья #1", "Семья #2", "Хобби #1", "Хобби #2", "Хобби #3", "Отношения", "Работа", "Рутина", "Деньги #1",
         " Несчастные случаи"],
        ["Дом # 1", "Дом # 2", "Кухня # 1", "Кухня # 2", "Кухня # 3", "Ванная и туалет #1", "Ванная и туалет #2",
         "Спальня", "Гостиная. ", "Столовая"],
        ["Здания #1", "Здания #2", "Здания #3", "Здания #4", "Здания #5", "Здания #6", "Улица #1", "Улица #2",
         "Транспорт #1", "Транспорт #2"],
        ["Овощи # 1", "Овощи # 2", "Фрукты # 1", "Фрукты # 2", "Ягоды", "Крупы", "Орехи", "Мясо и птица",
         "Морепродукты и рыба", " Напитки "],
        ["Планеты и космос", "Земля # 1", "Земля # 2", "Земля # 3", "Явления природы", "Явления природы",
         "Времена года и погода", "Растения", "Деревья", " Цветы"],
        ["Домашние животные", "Домашние животные", "Дикие животные # 1", "Дикие животные # 2", "Дикие животные # 3",
         "Дикие животные # 4", "Дикие животные # 5", "Птицы # 1", "Птицы #2", "Насекомые"],
        ["Образование #1", "Образование #2", "Образование #3", "Предмет исследования #1", "Предмет исследования #2",
         "Спорт #1", "Спорт #2", "Спорт #3", "Спорт # 4 ", " Спорт #5 "],
        ["Профессии  #1", "Профессии  #2", "Профессии  #3", "Профессии  #4", "Профессии  #5", "Профессии  #6",
         "Профессии  #7", "Профессии  #8", " Профессии  #9", "Профессии  #10"]
    ]
]

WORDS = ['word 1', 'word 2', 'word 3', 'word 4', 'word 5', 'word 6', 'word 7', 'word 8', 'word 9', 'word 10']

TRANSLATION = [
    ['sign in', 'Einloggen', 'Iniciar sesión', 'connectez-vous', 'войти'],
    ['android application', 'Android-Anwendung', 'aplicación para android', 'application Android', 'Android приложение'],
    ['IOS application', 'IOS-Anwendung', 'aplicación para iOS', 'Application IOS', 'IOS приложение'],
    ['Login to keep your progress', 'Melden Sie sich an, um Ihren Fortschritt zu speichern', 'Inicia sesión para guardar tu progreso', 'Connectez-vous pour enregistrer votre progression', 'Войдите, чтобы сохранить свой прогресс'],
    ['or', 'oder', 'o', 'ou alors', 'или'],
    ['Do not have an account? ', 'Haben Sie kein Konto?', '¿No tiene una cuenta?', "Vous n'avez pas de compte?", 'Нет аккаунта?'],
    ['register', 'registrieren', 'registrar', 'enregistrer', 'регистрация'],
    ['Create an account to save your progress', 'Erstellen Sie ein Konto, um Ihren Fortschritt zu speichern', 'Crea una cuenta para guardar tu progreso', 'Créez un compte pour enregistrer votre progression', 'Создайте аккаунт, чтобы сохранить свой прогресс'],
    ['passwords are different', 'Passwörter sind anders', 'las contraseñas son diferentes', 'les mots de passe sont différents', 'пароли различаются'],
    ['email is not valid', 'Email ist ungültig', 'El correo no es válido', "L'email n'est pas valide", 'email не действителен'],
    ['download', 'Download', 'descargar', 'Télécharger', 'скачать'],
    ['More topics to learn', 'Weitere Themen zum Lernen', 'Más temas para aprender', 'Plus de sujets à apprendre', 'Больше тем для изучения'],
    ['No advertisement', 'Keine Werbung', 'sin publicidad', 'Pas de publicité', 'без рекламы'],
    ['start', 'beginnen', 'comenzar', 'commencer', 'начать'],
    ['next word', 'nächstes Wort', 'siguiente palabra', 'mot suivant', 'следующее слово'],
]
